on: workflow_dispatch

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Print info
        run: |
          echo "::group::pwd"
          pwd
          echo "::endgroup::"
          
          echo "::group::ls -l"
          ls -l
          echo "::endgroup::"
          
          echo "::group::Branch"
          git branch
          echo "::endgroup::"

          echo "::group::Status"
          git status
          echo "::endgroup::"

      - name: Checkout 'latest'
        uses: actions/checkout@v4
        with:
          ref: latest
          fetch-depth: 0
          token: ${{ secrets.personal_access_token }}
      - name: Print info
        run: |
          echo "::group::pwd"
          pwd
          echo "::endgroup::"
          
          echo "::group::ls -l"
          ls -l
          echo "::endgroup::"

          echo "::group::Branch"
          git branch
          echo "::endgroup::"

          echo "::group::Status"
          git status
          echo "::endgroup::"
      - name: Bump latest
        run: |
          echo "::group::Merge and push"
          git merge --ff-only main
          git push
          echo "::endgroup::"
