on:
  workflow_dispatch:
    inputs:
      a:
        description: 'a'
        type: boolean
        default: false
      b:
        description: 'b'
        type: boolean
        default: false

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump
        if: ${{ github.event.inputs.a == 'true' && github.event.inputs.b == 'true' }}
        run: |
          echo "Minimal-overhead checkout"
          git fetch origin latest
          git branch latest FETCH_HEAD
          git checkout latest

          echo "Merge and push"
          git merge --ff-only
          git push

          echo "Go back!"
          git checkout -

          echo "Where am I?"
          git branch
