on: workflow_dispatch

jobs:
  must-fail--set-e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          set +e
          grep -qF "TODO" CONTAINS.md
          test $? -eq 1

  must-crash--set-e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          set +e
          grep -qF "TODO" DOES-NOT-EXIST.md
          test $? -eq 1

  must-pass--set-e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          set +e
          grep -qF "TODO" NO-CONTAINS.md
          test $? -eq 1

  must-fail--negate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          ! grep -qF "TODO" CONTAINS.md

  must-crash--negate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          ! grep -qF "TODO" DOES-NOT-EXIST.md

  must-pass--negate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          ! grep -qF "TODO" NO-CONTAINS.md
