on: workflow_dispatch

jobs:
  my-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Reset version number and changelog
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          sed -i "s/version=.*/version=9.9.9-unreleased/" gradle.properties
          sed -i "s/# Changelog/# Changelog\n## 9.9.9-unreleased\n### Added\n### Changed\n### Deprecated\n### Removed\n### Fixed\n### Security\n\n/" CHANGELOG.md

          git config --global user.name "fwdekkerbot"
          git config --global user.email "bot@fwdekker.com"
          git add --all
          git commit -m "Reset version number and changelog"
               
          git push origin main
