on: workflow_dispatch

jobs:
  must-fail--e-enabled--on-one-line:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          grep -qF "TODO" CONTAINS.md; test $? -eq 1

  must-fail--e-enabled--on-two-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          grep -qF "TODO" CONTAINS.md
          test $? -eq 1

  must-fail--e-disabled--on-one-line:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          set +e
          grep -qF "TODO" CONTAINS.md; test $? -eq 1

  must-fail--e-disabled--on-two-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          set +e
          grep -qF "TODO" CONTAINS.md
          test $? -eq 1
          

  must-crash--e-enabled--on-one-line:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          grep -qF "TODO" DOES-NOT-EXIST.md; test $? -eq 1

  must-crash--e-enabled--on-two-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          grep -qF "TODO" DOES-NOT-EXIST.md
          test $? -eq 1

  must-crash--e-disabled--on-one-line:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          set +e
          grep -qF "TODO" DOES-NOT-EXIST.md; test $? -eq 1

  must-crash--e-disabled--on-two-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          set +e
          grep -qF "TODO" DOES-NOT-EXIST.md
          test $? -eq 1


  must-pass--e-enabled--on-one-line:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          grep -qF "TODO" NO-CONTAINS.md; test $? -eq 1

  must-pass--e-enabled--on-two-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          grep -qF "TODO" NO-CONTAINS.md
          test $? -eq 1

  must-pass--e-disabled--on-one-line:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          set +e
          grep -qF "TODO" NO-CONTAINS.md; test $? -eq 1

  must-pass--e-disabled--on-two-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main'
        uses: actions/checkout@v4
      - name: Check
        run: |
          set +e
          grep -qF "TODO" NO-CONTAINS.md
          test $? -eq 1
