name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  check-release-needed:
    # Note that 'workflow_dispatch' is never skipped
    if: "!(contains(github.event.head_commit.message, '[cd skip]') || contains(github.event.head_commit.message, '[skip cd]'))"
    runs-on: ubuntu-latest
    steps:
      - name: nop
        run: true

  build-linux:
    needs: [ check-release-needed ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fwdekker/mommy
      - name: Install fpm and build dependencies
        run: |
          sudo apt install -y rubygems libarchive-tools rpm zstd
          sudo gem install --no-document fpm
      - name: Build packages
        run: make dist/generic dist/apk dist/deb dist/rpm dist/pacman
      - name: Upload built package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/mommy*

  release-mommy:
    needs: [ build-linux ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fwdekker/mommy
      - name: Download built packages
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Extract version number
        run: echo "MOMMY_VERSION=v$(head -n 1 ./version)" >> $GITHUB_ENV
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          release_notes_file: RELEASE_NOTES.md
      - name: Checkout release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: ${{ env.MOMMY_VERSION }}
          body_path: RELEASE_NOTES.md
          files: mommy*

  release-deb:
    needs: [ release-mommy ]
    runs-on: ubuntu-latest

    steps:
      - name: Download built packages
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: mommy-dist
      - name: Checkout mommy
        uses: actions/checkout@v4
        with:
          repository: fwdekker/mommy
          path: mommy
      - name: Checkout test-deb
        uses: actions/checkout@v4
        with:
          repository: fwdekker/test-deb
          path: mommy-deb
          token: ${{ secrets.personal_access_token }}
      - name: Extract version number
        run: echo "MOMMY_VERSION=v$(head -n 1 ./mommy/version)" >> $GITHUB_ENV
      - name: Import GPG key
        run: echo "$gpg_private_key" | gpg --import
        env:
          gpg_private_key: ${{ secrets.gpg_private_key }}
      - name: Update mommy-deb
        run: |
          echo "::group::Place .deb"
          mkdir -p mommy-deb/deb/
          cp mommy-dist/*.deb mommy-deb/deb/
          echo "::endgroup::"

          echo "::group::Update repo"
          cd mommy-deb/
          ./update.sh
          echo "::endgroup::"

          echo "::group::Commit update"
          git add --all
          git config --global user.name "FWDekkerBot"
          git config --global user.email "bot@fwdekker.com"
          git commit -am "🔖 mommy added package mommy $MOMMY_VERSION~"
          echo "::endgroup::"

          echo "::group::Push changes"
          git push origin
          echo "::endgroup::"
