on:
  workflow_dispatch:
    inputs:
      a:
        description: 'dry run'
        type: boolean
        default: false
      b:
        description: 'create mommy release'
        type: boolean
        default: false

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "&& inside {{}}"
        if: ${{ github.event.inputs.a == 'true' && github.event.inputs.b == 'true' }}
        run: echo "OK!"
      - name: "&& outside {{}}"
        if: ${{ github.event.inputs.a == 'true' }} && ${{ github.event.inputs.b == 'true' }}
        run: echo "OK!"
