on: [push]
jobs:
  netbsd-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: vmactions/netbsd-vm@v1
        with:
          run: |
            set -e

            touch packlist buildinfo

            echo "::group::Without buildinfo"
            /usr/sbin/pkg_create -c -comment -d -desc -f packlist pkg-name.tgz
            echo "::endgroup::"

            echo "::group::With buildinfo"
            /usr/sbin/pkg_create -B ./buildinfo -c -comment -d -desc -f packlist pkg-name.tgz
            echo "::endgroup::"
