name: CD

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        default: true

jobs:
  pre-flight-checks:
    runs-on: ubuntu-latest
    outputs:
      mommy_version: ${{ steps.output_version.outputs.MOMMY_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fwdekker/mommy
      - name: Fetch tags
        # Using `fetch-tags` option of `actions/checkout` does not work properly!
        run: git fetch --prune --unshallow --tags
      - name: Extract mommy's version number
        run: echo "MOMMY_VERSION=v$(head -n 1 ./version)" >> "$GITHUB_ENV"
      - name: Output mommy's version number
        id: output_version
        run: echo "MOMMY_VERSION=$MOMMY_VERSION" >> "$GITHUB_OUTPUT"
      - name: Check if release already exists
        run: |
          ! git show-ref --tags "v1.2.0" --quiet

  run-a-thing:
    needs: [ pre-flight-checks ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ ! github.event.inputs.dry_run }}
        with:
          repository: fwdekker/mommy
