name: CD

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test
        uses: actions/checkout@v4
        with:
          repository: fwdekker/test
          path: test
          fetch-depth: 0
      - name: Checkout test-deb
        uses: actions/checkout@v4
        with:
          repository: fwdekker/test-deb
          path: test-deb
          fetch-depth: 0
          token: ${{ secrets.personal_access_token }}
      - name: Import GPG key
        run: echo "$gpg_private_key" | gpg --import
        env:
          gpg_private_key: ${{ secrets.gpg_private_key }}
      - name: Update test-deb
        run: |
          echo "::group::Place .deb"
          mkdir -p test-deb/deb/
          cp test/mommy-1.2.4.deb test-deb/deb/
          echo "::endgroup::"

          echo "::group::Update repo"
          cd test-deb/
          ./update.sh
          echo "::endgroup::"

          echo "::group::Commit update"
          git add --all
          git config --global user.name "FWDekkerBot"
          git config --global user.email "bot@fwdekker.com"
          git commit -am "le update :3"
          echo "::endgroup::"

          echo "::group::Push changes"
          git push origin
          echo "::endgroup::"
