name: CD

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run"
        type: boolean
        default: true

jobs:
  dry-run:
    name: Dry run?
    runs-on: ubuntu-latest
    steps:
      - run: |
          [ "${{ github.event.inputs.dry_run }}" = "true" ]

  pre-flight-checks:
    env:
      is_dry_run: ${{ github.event.inputs.dry_run }}

    runs-on: ubuntu-latest
    outputs:
      mommy_version: ${{ steps.output_version.outputs.MOMMY_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fwdekker/mommy
      - name: Fetch tags
        # Using `fetch-tags` option of `actions/checkout` does not work properly!
        run: git fetch --prune --unshallow --tags
      - name: Extract mommy's version number
        run: echo "MOMMY_VERSION=v$(head -n 1 ./version)" >> "$GITHUB_ENV"
      - name: Output mommy's version number
        id: output_version
        run: echo "MOMMY_VERSION=$MOMMY_VERSION" >> "$GITHUB_OUTPUT"
      - name: Check if release already exists
        if: ${{ github.event.inputs.dry_run == 'false' }}
        run: |
          ! git show-ref --tags "$MOMMY_VERSION" --quiet

  run-a-thing:
    env:
      is_dry_run: ${{ github.event.inputs.dry_run }}

    needs: [ pre-flight-checks ]
    runs-on: ubuntu-latest
    steps:
      - name: Check in yml
        if: ${{ github.event.inputs.dry_run == 'false' }}
        run: |
          echo "::group::NOT A DRY RUN"
          echo "::endgroup::"
      - name: Check inside run
        run: |
          if [ "${{ github.event.inputs.dry_run }}" = "false" ]; then
            echo "::group::NOT A DRY RUN"
            echo "::endgroup::"
          else
            echo "::group::A DRY RUN"
            echo "::endgroup::"
          fi;
