on: [push]
jobs:
  netbsd-job:
    runs-on: ubuntu-latest
    steps:
      - uses: vmactions/netbsd-vm@v1
        with:
          prepare: |
            set -e
            export PATH="/usr/sbin:$PATH"  # Add 'pkg_*' commands to path

            touch packlist buildinfo

            echo "::group::Without buildinfo"
            pkg_create -c -comment -d -desc -f packlist pkg-name.tgz
            echo "::endgroup::"

            echo "::group::With buildinfo"
            pkg_create -B ./buildinfo -c -comment -d -desc -f packlist pkg-name.tgz
            echo "::endgroup::"
