name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-release-needed:
    if: "!(contains(github.event.head_commit.message, '[cd skip]')|| contains(github.event.head_commit.message, '[skip cd]'))"
    runs-on: ubuntu-latest
    steps:
      - name: nop
        run: true

  action1:
    needs: [ check-release-needed ]
    runs-on: ubuntu-latest
    steps:
      - name: Action
        run: true

  action2:
    needs: [ check-release-needed ]
    runs-on: ubuntu-latest
    steps:
      - name: Action
        run: true
